TagStudioDev/TagStudio

tagstudio/src/qt/ts_qt.py

Fixes the visual Bug at Bootup as mentioned in #9

Update ts_qt.py to fix bootup bug

---

tagstudio/src/core/library.py

Fixes #38 
You checked for default tags before adding any tags to check to it (in the to_json method).
Also fixed wrong return type of verify_default_tags

Update library.py to not duplicate default tags on save

---

doc/documentation.md

docs: update documentation.md

---

tagstudio/src/qt/ts_qt.py

To access, go to Edit > Tag Database.

A simple Tag Database.

---

tagstudio/src/qt/ts_qt.py

Fixes issue with badges not getting updated if meta tags gets removed

---

tagstudio/src/qt/ts_qt.py

This should fix issue #86 Because now Threads are exited correctly before quitting the application

Shuts the threads down before quitting the application Fixes #86

---

tagstudio/src/qt/modals/folders_to_tags.py

- Refractor to split UI from core functionality
- Fixed UI bug
- Added Open/Close all buttons

Folders to tags refractor + Bug fix + Enhancement  

---

tagstudio/src/qt/ts_qt.py

I don't know if there is anything to change about the way I currently reset the window.
I've tried to get some idea of the function of reopening a Libaray when one was already open.

added action to close a library

---

tagstudio/src/qt/ts_qt.py

Fix library reopen doesn't check if path is valid #118

---

tagstudio/src/qt/modals/tag_database.py

Remove Commented lines
Modify update_tags to always use tag ids (this might be considered for changes later)
Modify update_tags to avoid possibility of different behavior based on if a query was entered or not. 
Remove unused `panel: BuildTagPanel`

Remove functionally duplicated code in update_tags

---

tagstudio/src/qt/widgets/preview_panel.py

Add hand cursor (👆) for thumbnail and file path in sidebar to indicate these elements are interactive.

feat: add hand cursor for active sidebar elements

---

tagstudio/src/qt/widgets/panel.py
tagstudio/src/qt/widgets/text_line_edit.py

fix input enterPressed event

---

.github/workflows/apprun.yaml
requirements-dev.txt
requirements.txt
tagstudio/src/qt/ts_qt.py
tagstudio/tag_studio.py

When working on some of previous changes, it caused an issue when running the app without me noticing. This should run the app in CI to see if no error happens.

ci: try to run the app

---

.github/workflows/release.yml

Correct upload binaries used in release workflow

---

tagstudio/src/qt/widgets/preview_panel.py

fix sidebar expanding

---

tagstudio/src/qt/ts_qt.py

fix: update recent libs when creating new one

---

tagstudio/tag_studio.py

this makes editing the open option easier

Same short and long open option

---

mkdocs.yml

Update site_url in mkdocs.yml

---

CONTRIBUTING.md

Removed unnecessary "with" in "- Lint code *with* by [doing x]"
fixes #453

fix small grammar mistake in CONTRIBUTING.md

---

README.md

Correcting the link from Planned features to Roadmap.

fix: Corrected link to lead to the roadmap.

---

CONTRIBUTING.md
README.md
docs/index.md
docs/updates/roadmap.md
mkdocs.yml

docs: fix link to the feature roadmap page

---

requirements.txt

Reverts TagStudioDev/TagStudio#353

Revert "Update Numpy to version 2.1.0"

---

tagstudio/src/qt/modals/tag_search.py

As mentioned in #683
close #683

fix: [Bug] Close add tag menu only if no search is present

---

docs/install.md

Adds a notice about possible missing packages on Linux:
https://github.com/TagStudioDev/TagStudio/discussions/182
https://github.com/TagStudioDev/TagStudio/issues/393

docs: add a linux install notice

---

tagstudio/src/qt/widgets/item_thumb.py

Fixes #706 
Let me know if this is alright

Fix: [Bug] Can't Drag Out Multiple Files

---

tagstudio/src/qt/modals/about.py

feat(about): clickable links to docs/discord/etc in about modal

---

docs/library/tag.md

slight spelling mistake
[...] Fredddy's -> Freddy's

docs: Fix slight spelling error

---

.github/PULL_REQUEST_TEMPLATE.md

Just a simple PR template, adds important disclaimers and a task section to serve as context for reviewers.

chore(ci): add PR template

---

README.md

docs: correct spelling of Category

---

docs/develop.md
docs/library/entry.md
docs/library/field.md
docs/library/library_search.md
docs/library/tag.md
docs/library/tag_categories.md
docs/library/tag_color.md
docs/updates/roadmap.md
docs/updates/schema_changes.md
docs/usage.md
docs/utilities/macro.md

Light set of changes addressing general grammar oversights and standardizing local path formatting for relative links.
-   Platforms Tested: (unrelated)

Docs maintenance pass
