TagStudioDev/TagStudio

tagstudio/src/qt/ts_qt.py

Before this Refresh Directorys/Save Library/Save Library Backup (in File Menu) would throw an exception if no library was loaded this prevents that.

Prevent exceptions when no Library is Loaded

---

requirements.txt

Enables the program to be run with python3.12 aswell as supporting older version.
Pyside6 is purposly limited to 3.6.3.1 because 3.7 seems to have a bug that breaks the programm(should be [this ](https://bugreports.qt.io/browse/PYSIDE-2675) )that will hopefully be fixed in 3.7.1. 
All other versions are corectly selected by pip
(Tested with 3.10 and 3.12)
it should also work with 3.9.6 because all original versions of the packages are in the range described in this file.

python 3.12 support

---

README.md
TagStudio.sh
flake.lock
flake.nix

- Add necessary flake files to allow for a NixOS development environment.
- Update the `TagStudio.sh` bash script to use `/usr/bin/env bash` instead of `/bin/bash` to allow NixOS to run it.
- Update `README.md` with documentation on running the Nix environment.
Can now run `nix develop` on Nix, and then can run the TagStudio script and the application will launch as expected. 
Let me know if anything needs fixing!
_Note to any Nix people: The way I setup the environment is probably needlessly obtuse, but I got the app launching. This can probably be a lot simpler if someone has a smarter way of doing it._

Add NixOS Dev Environment Support

---

tagstudio/src/qt/ts_qt.py

Uses subprocess.Popen() along with start/open/xdg-open to open a file in its respective program. This process will last even after the TagStudio process exits.
Note: **this has only been tested on Linux!**
---
Recreation of #42.

 Allow files to be opened in their respective programs in the background for Windows, MacOS, and Linux

---

tagstudio/src/qt/ts_qt.py

Adds a QSettings object to the QtDriver, saves the last library on exit and auto reloads that library on next launch
To keep from polluting system/user directories and/or the windows registry an `.ini` format is used with the storage path overwritten to the cwd at time of launch.

QOL Open last opened library

---

tagstudio/src/qt/ts_qt.py

Tite. Path needs to be wrapped in quotes, and any inner quotes are escaped.
Note: untested as I am on Linux.

Windows: fix files w/ spaces opening cmd rather than associated program

---

tagstudio/src/qt/ts_qt.py

Tag Studio has some common keyboard shortcuts now:
- Opening/Creating Library (Ctrl+O)
- Saving Library (Ctrl+S)
- Saving Backup (Ctrl+Shift+S)
- Refresh Library (Ctrl+R)
- New Tag (Ctrl+T)
- Sort Fields (Alt+S)

Keyboard Shortcuts

---

tagstudio/src/core/ts_core.py
tagstudio/src/qt/ts_qt.py

Adds a new button to the tools menu that creates tags based on the folder structure and applies them to entries

Add folders to tags tool

---

tagstudio/src/cli/ts_cli.py
tagstudio/src/core/library.py
tagstudio/src/core/ts_core.py
tagstudio/src/qt/ts_qt.py

Hi,
this PR aims to simplify some pieces of code to improve readability. Beside that there's a few tiny fixes for potential bugs (see my comments on given lines)

improve code readability

---

tagstudio/src/core/json_typing.py
tagstudio/src/core/library.py

Wip:
Adds a new file `json_typing.py` that includes `TypedDict` declarations for the json file format
Then uses those thoughout core where nessesary.
The main benefit is strict typing checking then making and reading the json
Unfinished work:
- `fields`, I couldn't work out that is being stored or loaded here
- `macros`, I can't actually tell if these are used

🏷️ Add strict typing dicts for ts_library.json

---

tagstudio/src/qt/ts_qt.py

Fixes: #81
Refactored file opener helper to use already present open_file
Refactored open_file to allow option for file manager
For Linux systems, should use default file manager.
**IMPORTANT: only tested on Linux!**
This as well prevents a freeze from the previous implementation that used subprocess.run, which is a blocking operation.

Allow opening and selecting files in file managers for all platforms

---

tagstudio/src/core/library.py

I dont know where exactly the issue occurs, but for now this is good enough to fix the issue.
The issue is where files are inserted into library with leading slash, eg. "/photo.jpg" instead of "photo.jpg". That's because when `entry.path` is empty, the result is just the slash + filename.
Then when I refresh the library, `photo.jpg` isnt there apparently there (only `/photo.jpg`), so it gets inserted again as a duplicity.

fix: strip leading slash in library items

---

tagstudio/src/core/library.py

https://github.com/TagStudioDev/TagStudio/blob/93177dd696aaeacb1041013dd9a4b0c1d77066e3/tagstudio/src/core/library.py#L690-L699
causes fields to load into memory as `list[dict[str,list[int]]]` instead of list[dict[int,list[int]]]
This causes #93 and leads to unintended cases of #92
Fixes #93

Patch Bug that prevents loading ts_library.json fields ids as integers

---

tagstudio/src/core/library.py
tagstudio/src/qt/modals/tag_search.py

Right now when I want to add new tag to file via the "Add Tag" panel window, I have to trigger update of tags manually via typing into the search input. Is there any actual reason behind this? If I have a trivial number of tags, I want to see them straight away without typing anything. That's the change this PR introduces.
Beside that the empty value for `self.first_tag_id` is now `None` instead of `-1` to see better it's actually non-tag value, plus it will fail loudly in case the it would get passed somewhere it shouldnt.

show all tags in Add Tags panel by default

---

.github/workflows/ruff.yaml
.pre-commit-config.yaml
README.md
pyproject.toml
requirements-dev.txt

The current PR is quite huge, as the code has totally different styling all across the places (mixing tabs/spaces, single/double quotes, inconsistent spacing etc.), but having unified coding style is benefit in a long term.
Currently there are no enforced code styling rules other than a mild recommendation "something like pep8" in README. 
Nitpicking and bikeshedding about code formatting in PRs is not very productive, and if something can be automated then let's automate it. 
This PR is adding a job for automatic check of code formatting. If the style doesnt follow what ruff expects, it will show failing badge in PR. See example here: https://github.com/yedpodtrzitko/TagStudio/pull/1
But to make the action pass, we need to format all existing files to match the style.
To format the code, …

add code formatting & Github Action via ruff

---

tagstudio/src/core/utils/web.py

This allows for more prefixes to be added in the future if needed without repeating code multiple times.

Refactor strip_web_protocol()

---

tagstudio/src/qt/helpers/file_opener.py

Unsure if this is exactly to style, but it should resolve #120 
Simply wrapping the path in quotes did not suffice, there seems to be some weird edge case in `.Popen()` with args containing quotes

Fix opening to a file with spaces in path on windows / #120

---

tagstudio/src/qt/modals/tag_search.py
tagstudio/src/qt/widgets/tag_box.py

There was a bug if you added a tag and then directly afterwards (without selecting another element) wanted to add a tag to a field, the tag was not displayed at first, only when the `update_tag` function was called once.
and I gave the `update_tag` function an empty query as default so you don`t have to pass an empty string when you call it.

minor bug fixes to Tag Search Box

---

TagStudio.sh

"set -e" to abort on error
"cd …" to prevent creating .venv if script is launched from outside git dir
"[ … ]" to skip creating venv when it already exists

Improved TagStudio.sh

---

tagstudio/src/qt/ts_qt.py

This should resolve #119 
Simply prompts the user to select a new directory if `self.lib.save_library_to_disk()` throws a `FileNotFoundError`

Fix for #119, Prompt for new location user if library cannot be saved

---

.gitignore
Build_win.bat
requirements.txt

Adds a build script for a windows executable
It intentionally doesn't hide the console for the exe because windows defender then complains that it is a malicious programm.
Also i oriented the build script of of the mac os build script from @williamtcastro

Build Script for windows

---

tagstudio/src/qt/ts_qt.py

Add "Go to GitHub Repository" to the help menu.

Add action to help menu

---

tagstudio/src/qt/ts_qt.py

Currently the worker threads are running in a loop and raise `Empty` error each time when `queue.get()` in there timeouts (ie. every 0.2 seconds) and repeat the same thing again, which is not very clean.
This PR makes call of `queue.get()` blocking, so there's no need for the exception-raising mumbo jumbo. Previously there was problem with this approach on application shutdown. So now when the app is quitting, there's a marker put into the queue to notify the thread it should terminate itself.
Tested on macOS only.

dont run job threads needlessly

---

tagstudio/src/qt/pagination.py

Refactors ~200 lines of chained and fairly duplicate if-else's down to ~20 lines.

Refactor:  Deduplication in pagination.py's  "Set Elipses Sizes" section

---

tagstudio/src/qt/widgets/item_thumb.py

- code for toggling archived and favorite tag is kinda' duplicate, plus each of these methods has some redundant code within as well.
- use identifiers for the archived/favorite tag instead of non-descriptive int values.

misc: remove duplicate code for tags updating

---

tagstudio/src/core/enums.py
tagstudio/src/core/ts_core.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/preview_panel.py

superseding #127
- show list of previously opened libraries on bottom of sidebar:
- add option (default True) to decide if previous library should be opened on app start
- there's a minor refactoring to keep working with variables localized. So instead of this:
```
root_layout = QHBoxLayout(self)
root_layout.setContentsMargins(0, 0, 0, 0)
root_layout.addWidget(splitter)
```
...working with the variable is now moved into the same place.

add list of libraries into sidebar

---

tagstudio/src/qt/widgets/preview_panel.py

Added a step to clear the edit button within the write_container().  This shouldn't interfere with the edit button showing, as its default behavior is to be hidden until a hover event.

fix: Clear Edit Button on container update (#115)

---

.github/workflows/mypy.yaml

this improves the way how mypy errors can be checked. Instead of going to the logs, the errors will be added as comments on relevant lines, see:
https://github.com/yedpodtrzitko/TagStudio/pull/2/files#file-tagstudio-src-core-library-py-L529

use reviewdog for mypy job

---

tagstudio/src/qt/ts_qt.py

feat: add select all hotkey

---

requirements.txt
tagstudio/src/core/constants.py
tagstudio/src/core/library.py
tagstudio/src/core/utils/encoding.py
tagstudio/src/qt/widgets/preview_panel.py
tagstudio/src/qt/widgets/thumb_renderer.py

Some small bugfixes and improvements involving thumbnail and preview rendering:
- Fix RAW images not being loaded correctly in the preview panel
- Fix trying to read size data from null images
- Refactor `os.stat` to `<Path object>.stat()`
- Remove unnecessary upper/lower conversions
- Improve encoding compatibility beyond UTF-8 when reading text files
- Misc. code cleanup

Fix Raw Image Handling and Improve Text File Encoding Compatibility

---

tagstudio/src/core/enums.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/preview_panel.py

If the latest opened library no longer contains a `TS_FOLDER_NAME` (currently `.TagStudio`) folder clear the recent library and revert to default behavior for opening TagStudio. 
NOTE: if the library moves to a different architecture (e.g. living alongside preference instead of alongside the files this check will need to be removed)
Fixes #212

Bugfix for recent library re-creating a library at the last library location.

---

tagstudio/src/qt/ts_qt.py

Resolve issues where the open library dialog will try to open `.` if no path is returned from the dialog
Fixes #239

Bugfix Open Library Dialog

---

tagstudio/src/core/library.py
tagstudio/src/qt/modals/file_extension.py

Adds leading `.` to default extensions
Adds item delegate for Ignored File Extension to add leading `.` if left off extension

Fix Default Ignored File Extension

---

tagstudio/src/core/constants.py

I added various file formats to the constants.py file, including ".dmg", ".s7z", ".cr2", ".jar", ".msi"

Added various file formats to constants.py

---

.github/workflows/apprun.yaml
.github/workflows/mypy.yaml
.github/workflows/release.yml

Ocassionally, a pip install will fail because of mismatched hashes, which from my research I believe this to be related to a cache error. This cannot easily be tested due to its seemingly random nature, but my hope is that my fix in using the action/setup-python workflow will avoid it.
Additionally, the MacOS version needs to be bumped, as `macos-11` has been deprecated. 11 is still targeted for compatibility. See [this blog post](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/) for more information.

Workflows: attempt fix for mismatched hashes in pip and bump MacOS version

---

tagstudio/src/core/json_typing.py
tagstudio/src/core/library.py
tagstudio/src/qt/modals/file_extension.py
tagstudio/src/qt/ts_qt.py

I added the option to invert the ignored extension list like its mentioned in #230.

Add option to use a allowed extensions instead of ignored extensions

---

tagstudio/src/qt/ts_qt.py

Simply lets you clear the current entry selection through the Edit -> Clear Selection button, or by pressing Ctrl+D. A minor feature I think would be very convenient.
I am quite unfamiliar with both Python and Qt, so please let me know if there is anything I should change or improve.

Add "Clear Selection" button

---

flake.lock
flake.nix

By pinning QT separately, the rest of dependent nixpkgs can be updated without being affected by the current QT version in nixpkgs unstable. The nixpkg revision is also bumped, fixing an issue where vim would immediately segfault on launch in the nix dev shell. This is for QT version 6.6.3, for when #223 is merged, the nixpkg commit tied to QT will need to be bumped to commit 47da0aee5616a063015f10ea593688646f2377e4. 
Also adds missing dependecies from the new video player.

Separately pin QT nixpkg version

---

tagstudio/src/qt/widgets/preview_panel.py
tagstudio/src/qt/widgets/thumb_renderer.py

Raise error if video file has 0 frames or is in valid.
video.get(cv2.CAP_PROP_FRAME_COUNT) returns 0 or -1
An addition change could be implemented by calling video.setExceptionMode(True) which would raise cv2 errors if other issues arise later.
Fixes #252

Bugfix for #252, don't attempt to read video file if invalid or 0 frames long

---

tagstudio/src/qt/widgets/item_thumb.py

This PR disables mouse event transparency for `ItemThumb` objects when their mode is set to `None` and enables it when set to any other mode. This stops hidden `ItemThumb`s from blocking mouse input when they overlap visible items in the grid view under specific circumstances. Fixes #256.

Toggle Mouse Event Transparency on ItemThumbs (Fix #256)

---

tagstudio/src/qt/modals/drop_import.py

Refactor excessively long f-string into separate variables to resolve issue
Fixes #288

fix: backslashes in f-string error on file drop dupe widget

---

.gitignore
tagstudio/tests/conftest.py

Edit the testing library fixture to create its files ad-hoc when it's used. When the library content will be updated in future, the files will be always up-to-date. Also in case when a test will delete file, another test will still have it available again.

create testing library files ad-hoc

---

README.md

I have just fixed an outdated link.
Btw. there are no instructions on how to commit changes to the docs in the CONTRIBUTING.md, so I have improvised this PR. Maybe that information is worth adding :)

docs: Fixed outdated link to markdown file.

---

tagstudio/src/core/constants.py
tagstudio/src/core/enums.py
tagstudio/src/core/library.py
tagstudio/src/core/ts_core.py
tagstudio/src/qt/modals/folders_to_tags.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/item_thumb.py
tagstudio/src/qt/widgets/tag_box.py

this PR puts all field IDs into one enum, and use that instead of numbers directly or ad-hoc created variables with given values.

refactoring: centralize field IDs

---

tagstudio/src/qt/widgets/preview_panel.py

This fixes Bug #305. I just forgot a line that prevents this warning when updating the Pyside version in pr #223.

Fixes Bug #305

---

tagstudio/src/qt/modals/add_field.py
tagstudio/src/qt/widgets/preview_panel.py

Use ListWidget instead of ComboBox, so multiple new fields can be added at the same time.

use list widget for selecting fields to add

---

tagstudio/src/core/constants.py
tagstudio/src/qt/helpers/text_wrapper.py
tagstudio/src/qt/widgets/preview_panel.py
tagstudio/src/qt/widgets/thumb_renderer.py

I added simple font thumbnail previews for .ttf, .otf and .woff files like it was requested in issue #304 . Currently there are three text sizes (10,12,15) that i selected. I stacked the sample text in the different font sizes next to each other and tried to dynamically fit them next to each other. I am open to changing how the text alignment works and other changes. At the moment it looks like this:

Add font thumbnail preview support

---

tagstudio/src/qt/modals/tag_database.py
tagstudio/src/qt/modals/tag_search.py

Sort tags in the Library Tags panel and the Add Parent Tags panel with Archived and Favorite at the top, then sort by color, and then sort alphabetically.
This is what the panels look like now when you have many tags of different colors:

feat(ui): sort tags in add tag panel by color/alphabetical (close #327)

---

tagstudio/src/qt/modals/folders_to_tags.py

Swaps the use of `branch["tag"]` for `branch.get("tag")` inside of `add_folders_to_tree()` to avoid a `KeyError` when there is no Tag.

fix: avoid `KeyError` in `add_folders_to_tree()` (fix #346)

---

CONTRIBUTING.md
flake.lock
flake.nix

When running `nix develop` to generate a development shell, the python virtual environment will now automatically be created and dependencies from requirements.txt will be installed (and the venv will be activated). Effectively, this moves the setup portion of the TagStudio.sh to the flake and means the setup script for Linux/Mac is no longer needed when using nix. The README has been updated to reflect the new process of `nix develop` then `python3 tagstudio/tag_studio.py`. 
The python virtualenvironment package has been replaced with venvShellHook, which creates a virtual environment in the directory specified by $venvDir (in this case ./.venv). This also gives the postVenvCreation hook, where pip install is then executed. The previous shellHook needed to be moved to postShellHook to …

Create and activate venv via Nix Flake

---

tagstudio/src/core/library.py
tagstudio/src/qt/modals/merge_tag.py
tagstudio/src/qt/widgets/tag.py

Added the ability to merge tags in the tags context menu (should this be in the manage tags modal only?). Merge tag adds the source tag name and aliases to the target tag, appends all subtags to the target tag, reassigns all entries to the target tag, and removes the source tag. 
Let me know if I'm missing anything in the merge process. Also, when the modal closes the ui state doesn't immediately show the merge. Any ways to make it more reactive?
Closes #12

Add Tag Merging

---

flake.nix

Fixes #417
Enables hardware accelerated video playback for Nix _devenv_.
Also supports VA-API compatible GPUs like AMD and Intel (also see [libva](https://github.com/intel/libva/blob/01153523f25ac703e7ce2afc0023788a90f6c1bb/va/drm/va_drm_utils.c#L62-L68) for reference).

GPU Hardware Acceleration for Nix Flake

---

tagstudio/src/core/library.py

fix(dupes): fix duplicate file matching
chore: remove constant newline printing in file matching

Fix duplicate removal

---

tagstudio/src/core/library.py
tagstudio/src/qt/modals/tag_database.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/tag.py

This PR addresses three related issues:
1. #211: "Search for Tag" context menu option + left-click behavior for tag widgets did not include tag clusters in results; only instances of that exact tag ID. Expected behavior is to include the entire inheritance cluster, and this has now been implemented. Additional commented-out code has been removed inside the `search_library()` method. 
2. "Add to Search" context menu option was non-functional. This option has been removed from the context menu.
3. Undocumented issue found during testing: The "Search for Tag" context menu and left-click behavior was non-functional for tag widgets inside the "Tag Manager" panel. This functionality has been implemented.
I have not updated the display of tag IDs in the search bar as discussed in 211, as I feel …

fix: correct behavior for tag widget search options

---

tagstudio/src/core/library.py
tagstudio/src/core/ts_core.py
tagstudio/src/qt/ts_qt.py

This Pull Request addresses 3 Bugs I found while using the gallery_dl-sidecar importing feature:
1. Running macros on files that aren't in a subdirectory was broken (see 1d4570174a3014cfaf348ae5752537528d9ed11e).
2. For `filename.jpg` `get_gdl_sidecar` would try to load `filename.json` instead of `filename.jpg.json`, which is the default filename format used by gallery_dl (see a0562a876630e7bd7fd0b3b91180c8c7bb32975c).
3. `add_generic_data_to_entry` would create a second Content Tags Field if the existing Content Tags field was the first field, because an if-statement used `>` instead of `>=` (see fbd2244a2eb27f9454c8d33006e5f443105fdcea).
I didn't create an Issue first because I had already fixed these issues in order to use the autofill macro to import gdl sidecar files.

Sidecar macro fixes

---

tagstudio/src/qt/ts_qt.py

easy backport from #332 which could be actually nice for the upcoming release
- All the modal windows (Folders to Tags etc.) are always instantiated immediately, which takes time.  This PR postpone them until it's actually needed, which speeds up the application start.
~- also reuse `UniversalDetector` instance for files encoding detection.~

Postpone instantiating modal windows

---

tagstudio/src/qt/widgets/preview_panel.py

This PR displays the file creation and modified dates in the preview panel, as well as restyles the file path label to make it appear more legible.
I understand that #429 is also aiming to restyle the the file path label, and perhaps these approaches can be consolidated. 
*Dark Theme*
*Light Theme*

feat(ui): show file creation/modified dates + restyle path label

---

tagstudio/src/qt/widgets/preview_panel.py

st_ctime does not provide accurate creation time on MacOS, and as Python 3.12 is [deprecated for Windows](https://docs.python.org/3.12/library/os.html#os.stat_result.st_ctime). On these two platforms st_birthtime is used instead.
Tested on Linux and Windows
fixes #469

fix(PreviewPanel): Use birthtime for creation time on Mac & Windows

---

tagstudio/src/qt/helpers/vendored/pydub/audio_segment.py
tagstudio/src/qt/widgets/thumb_renderer.py

When FFmpeg is missing, Popen raises a FileNotFound error. This would be caught as an Unlinked file and use the broken file icon. The exception is now caught and a more appropriate exception is raised in its place.
Fixes: #461

fix(ThumbRenderer): Use audio icon when no ffmpeg

---

docs/help/ffmpeg.md

An installation guide for installing FFmpeg on all platforms. Will be necessary now that FFmpeg is a hard depenedency

docs: Add ffmpeg installation guide

---

flake.nix

Follow #332, tagstudio would no longer start (on wayland) without adding x11 as a dependency to the library path.

fix(Flake): Add missing x11 dependency

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/qt/ts_qt.py
tagstudio/tests/conftest.py
tagstudio/tests/qt/test_driver.py

fix error on closing library

---

tagstudio/src/qt/ts_qt.py

Keeps the filtered query thumbnails in the main window, rather than before where the search would remain in the bar but the filter would be reset to none.
Fixes #482

fix(QtDriver): Retain filter on directory refresh

---

tagstudio/src/core/library.py
tagstudio/src/qt/modals/drop_import.py

This pull request significantly increases file scanning performance, especially for rescanning libraries and for libraries with a large file to folder ratio.
Using a test library with around ~200k files (~100k filtered out via the exclusion list) on a standard 5400 RPM HDD, and found an average increase in library rescanning times of around 23x:
```yaml
v9.4.0:
[LIBRARY]: Scanned directories in 88.160 seconds
[LIBRARY]: Scanned directories in 87.398 seconds
[LIBRARY]: Scanned directories in 90.164 seconds
[LIBRARY]: Scanned directories in 88.031 seconds
[LIBRARY]: Scanned directories in 87.657 seconds
Optimized:
[LIBRARY]: Scanned directories in 3.823 seconds
[LIBRARY]: Scanned directories in 3.796 seconds
[LIBRARY]: Scanned directories in 3.771 seconds
[LIBRARY]: Scanned directories in …
```

feat: increase file scanning performance

---

.github/workflows/mypy.yaml
tagstudio/src/core/library/alchemy/library.py
tagstudio/src/core/utils/refresh_dir.py
tagstudio/src/qt/ts_qt.py
tagstudio/tests/conftest.py
tagstudio/tests/macros/test_dupe_entries.py
tagstudio/tests/macros/test_refresh_dir.py
tagstudio/tests/qt/test_preview_panel.py

`refresh_dir()`:
~- now takes `exclude_list` into consideration~ edit: it probably shouldnt
- it also accepts new `Path` parameter in preparation for multiple-directory Library eventually
unrelated changes
- use `uv` to install dependencies even in `mypy` job to avoid dependencies download failure
- Library in tests now goes by default to `/dev/null/` instead of `/tmp/` to detect when some test is trying to touch the filesystem
- remove some unused properties from `Library`
- `.extension_list` was getting easily out of sync with database, so it's removed as well and it is just in DB now

cleanup the `refresh_dir` code, update tests

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/tests/test_library.py

Previously, searching for tags required % wildcards to be added either side in order to search for a tag without an exact match, however this removes that requirement.

Fix tag search to not require wildcards

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/core/utils/dupe_files.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/item_thumb.py
tagstudio/src/qt/widgets/preview_panel.py
tagstudio/tests/macros/test_missing_files.py
tagstudio/tests/test_library.py

the current return type of `search_library()` is a bit unergonomic - it returns a tuple of:
`(total_count, page_items)`, so the result needs to be assigned into two items, which is error-prone
This should make it better - it returns `SearchResult` which is a wrapper for `total_count` and `page_items`, but it can still be treated just as list of items

feat: make search results more ergonomic

---

tagstudio/tests/qt/test_driver.py

Just saw this when trying to read through stuff and thought I might fix it.
Priority: low

Fixed small Typo in a Comment in test_driver.py

---

tagstudio/src/core/library/alchemy/library.py

fix: dont check db version with new library

---

pyproject.toml

Prior to this change, running mypy from the root directory of the repo would log errors, because mypy couldn't find the referenced implementations for import statements like this one: `from src.qt.ts_qt import QtDriver`. This change tells mypy that it can find these implementations in the `tagstudio` directory.
Fixing this is necessary for the MyPy Extension for VSCode to work and it shouldn't break the existing workflows since running mypy in the `tagstudio` directory still yields the same results as before.

fix running mypy from project directory

---

.github/workflows/pytest.yaml

This pins the Ubuntu version for the pytest workflow to 22.04. This restores the workflow functionality, at least in the meantime while a proper fix for the Ubuntu 24 error is created.

ci: pin pytest ubuntu version to 22.04

---

tagstudio/src/core/library.py

This PR adds a basic library autosave feature which creates a copy of the library on load which can be automatically loaded in the event that the main library becomes blank or missing. In addition, this moves the `self.to_json()` call inside the library save method to outside of the `with` block as suggested in #343, which should prevent most cases of TagStudio writing a blank library to disk.
I'm looking at this as a bugfix to be added in a future 9.4.2 patch. Since 9.5/main uses a completely different SQLite backend, this change is really just to provide a bit more safety and stability for the current 9.4.x releases in the meantime. This "feature" will die with that branch and is effectively obsolete as-is (not to sound somber).

[9.4.x] Create auto-backup of library for use in save failures (Fix #343)

---

tagstudio/src/core/media_types.py
tagstudio/src/qt/widgets/preview_panel.py

fix resolution info #550

---

CONTRIBUTING.md

docs: update CONTRIBUTING.md ruff instructions

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/tests/qt/test_qt_driver.py
tagstudio/tests/test_library.py

Implements the alternative searching mentioned in #577

feat: make path search use globs

---

tagstudio/src/qt/ts_qt.py

No need to keep rendering the queued thumbnails when closing library and/or quitting the app

remove queued thumnail jobs when closing library

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/qt/main_window.py
tagstudio/src/qt/ts_qt.py

currently, the autocomplete will automatically show up when the user types something that can be autocompleted (right now, "filetype:", "mediatype:", "tag:", "tag_id:", and "path:"). 
`filetype` and `mediatype`: autocompletes with all filetypes/mediatypes currently registered in tagstudio, regardless of whether the current library contains any files of a type.
`tag`: autocompletes with all tag names, case-insensitive
`tag_id`: autocompletes with ids of all tags
`path`: autocompletes with all paths currently stored in the library

feat: add autocomplete for search engine

---

tagstudio/src/qt/widgets/preview_panel.py

When removing fields from an entry the database would properly update, but the ui would not reflect those changes until a different entry was selected then switched back to the entry that was edited. This PR fixes that.

[fix] bug where preview panel ui would not update when fields where removed from an entry

---

tagstudio/src/qt/helpers/file_opener.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/preview_panel.py

Just four extremly short fixes in order to stop mypy from complaining constantly. Specifically:
- two type ignore comments threw unused-ignore on windows (but didn't on linux), the type ignores now also ignore unused-ignore
- a call in ts_qt was missing a trivial argument
- two variables in file_opener had the same name but different type and mypy wasn't happy about that, I renamed one appropriately

fix: shut up mypy

---

tagstudio/src/qt/helpers/file_opener.py

Fixed normpath variable using posix, leading to windows not understanding the command given to it (issue #602)

Fixed open in explorer does not open the correct folder

---

tagstudio/src/qt/widgets/fields.py
tagstudio/src/qt/widgets/preview_panel.py

Hi,
I removed the Warning that is shown in the console that occurs when Tagstudio is opened and a thumbnail is clicked for the first time.
Bug:
Fix:
Check if provided callback function is actually a Callable and preventing it from trying to disconnect when the callback is None.

Small fix: Remove unnecessary warning in console

---

tagstudio/tests/test_driver.py
tagstudio/tests/test_library.py

1. in `tagstudio/tests/test_driver.py::test_evaluate_path_last_lib_present` test, updated the test to explicitly define a `QSettings` file and format to address a bug causing test failures. previously, `QSettings()` was constructed without specifying an organization or application name. which per the documentation, prevents reading or writing settings. the new implementation creates a temporary settings file and uses it to save the settings. this ensures the test can properly save and read the settings.
2. `tagstudio/tests/test_library.py::test_save_windows_path` removed, which isnt' testing anything meaningfully.
resolves #616

fix: [Bug]: Path tests failing on Windows #616

---

tagstudio/src/qt/ts_qt.py

Added a check to see if the library is loaded in filter_items

---

requirements.txt

I Updated the Numpy version Tagstudio is running on, to the newest version compatible with rawpy and opencv. I also updated the version they are pinned to.
I tested it a bit but feel free to test yourself

Update Numpy to version 2.1.0

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/core/library/alchemy/models.py
tagstudio/src/qt/widgets/migration_modal.py

This PR fixes #627 by not allowing empty string values for tag aliases inside the database.

fix: don't allow blank tag alias values in db (Fix #627)

---

.github/workflows/pytest.yaml

This PR updates the pytest workflow to Ubuntu 24.04.

chore: update pytest workflow to 24.04

---

tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/tag_box.py

When changes were made to a tag using the tagDatabasePanel, those changes would not be reflected in the previewPanel.
When changes where made to a tag using the previewPanel, those changes would not be reflected in the database.

 fix: preview panel aliases not staying up to date with database

---

tagstudio/src/core/library/alchemy/db.py

This PR fixes #644 by having `make_tables` check the current autoincrement value (what the next inserted row would have as its id) on the `tags` table. Previously, an `INSERT` and a `DELETE` were always being run when a library was opened, causing the file change counter to increase
close #644 
close #646

fix: stop sqlite db from being updated while running tests

---

tagstudio/src/qt/modals/fix_unlinked.py

fixes use of count instead of self.missing_count
close #652

Fix: [Bug] "Fix Unlinked Entries" not functioning, only returns None count

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/core/library/alchemy/visitors.py

fix(#655): search now works again

---

docs/updates/roadmap.md
tagstudio/src/core/library/alchemy/visitors.py
tagstudio/src/core/media_types.py

Implements feature from the roadmap:
> Optional consolidation of extension synonyms (i.e. ".jpg" can equal ".jpeg")
More equivalencies can easily be added through modifying a constant in `src/core/library/alchemy/visitors.py`.
(No issue because this is a short PR and because I don't think anyone else is touching the search rn)

feat: implement search equivalence of "jpg" and "jpeg" filetypes

---

tagstudio/src/qt/modals/build_tag.py

fix for issue #664 
replaces subtag_ids list with a set to prevent duplicate tag parents

[Bug] Ui: Stop duplicate tag parents

---

tagstudio/src/core/driver.py
tagstudio/src/qt/ts_qt.py

fix: fix -o flag not working if path has whitespace around it

---

tagstudio/src/qt/helpers/file_opener.py

this change fixes #666 and #350.
entering files full path into cmd opens it in its associated program, and using that instead of "start" fixes the issues.
im assuming it has something to do with "start" being almost 30 years old at this point but this seems to fix it for me

[Bug] Allow files with non latin paths to be opened from preview

---

README.md

Just gonna make it a new PR, because GitHub web interface is insufferable, made two branches and I give up trying to merge them into one.
Same as the previous PR, but this time in readme
Adds a notice about possible missing packages on Linux:
https://github.com/TagStudioDev/TagStudio/discussions/182
https://github.com/TagStudioDev/TagStudio/issues/393

docs: add a linux install notice to readme

---

tagstudio/src/qt/modals/tag_database.py
tagstudio/src/qt/modals/tag_search.py

The refactor of `TagDatabasePanel` and `TagSearchPanel` mostly as previously discussed. The only two differences are:
- instead of a common super class that both inherit from `TagDatabasePanel` now inherits from `TagSearchPanel`
- the context menu option "Edit" is now also available in the Tag Search Panel. This was done for two reason:
1. simplification of the code
2. I have wanted to do that while using TS multiple times

refactor: TagDatabasePanel now inherits from TagSearchPanel for code deduplication

---

CONTRIBUTING.md

As agreed on the discord, a change to the contribution guidelines to discourage force-pushing on PRs that are open for review.
This change is meant to lighten the work of reviewers, because - due to the way that git works - when a force push happens after a review has already been made, or while a review is being made, it is not really possible to figure out which changes were already reviewed and which weren't. Thus a reviewer in this situation is forced to rereview a bunch of code that they have already reviewed (which is quite frustrating in my experience).

docs: discourage force-pushes on prs that are open for review

---

tagstudio/resources/translations/en.json
tagstudio/resources/translations/fr.json
tagstudio/src/qt/modals/tag_search.py

close #688 
- Ports the Create & Add tag to v9.5
- added translation keys (only one) for English and French
- unify use of BuildTagPanel to avoid multiple imports within functions
hope this is alright
(edit: to add images) 
Clicking create opens the Add Tag modal

Parity: Port create and add from v9.4 to v 9.5

---

tagstudio/src/qt/modals/folders_to_tags.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/item_thumb.py
tagstudio/src/qt/widgets/preview_panel.py
tagstudio/src/qt/widgets/tag_box.py

This PR provides a few fixes and optimizations regarding refreshing the preview panel and resetting the state of the main window UI as a whole when closing or switching libraries:
- The media file preview for the preview panel now only updates when necessary
- Before this would always update when information about the entry was modified, including when tags were added or even simply edited. Now operations such as adding tags no longer cause image thumbnails to re-render or for videos to restart.
- The preview panel is now cleared when closing or switching libraries
- The search bar is now cleared when closing or switching libraries
- The scrollbar position is now reset when closing or switching libraries
- The filter state, notably the page number, is now reset when switching libraries

fix: preview panel + main window fixes and optimizations

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/qt/modals/tag_search.py

fix for #687. added logic to sort the results of a tag search. currently prioritizing results that start with the correct string and sorting them by length, and then sorting all other results alphabetically. saw the todo comment, but i could not figure out a simple way of reusing the widgets, theyd probably have to be stored in a dict between updates or something.

fix: sort tag results

---

tagstudio/src/qt/ts_qt.py

Fix: [Bug] Open Last library on startup

---

tagstudio/src/qt/helpers/file_opener.py
tagstudio/src/qt/helpers/silent_popen.py
tagstudio/src/qt/helpers/vendored/ffmpeg.py
tagstudio/src/qt/helpers/vendored/pydub/audio_segment.py
tagstudio/src/qt/helpers/vendored/pydub/utils.py

By default, any subprocesses will inherit environment variables from its parent. Pyinstaller will specify a custom ```LD_LIBRARY_PATH```, which causes issues when the subprocess attempts to load its own dynamically linked libraries.
https://web.archive.org/web/20240824170055/https://github.com/TagStudioDev/TagStudio/issues/210
1. Implemented suggested solutions for linux and windows from https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#launching-external-programs-from-the-frozen-application. Doesn't really seem like a solution for MacOS is necessary based on the docs.
2. Renamed and slightly reworked promptless_Popen into silent_Popen (better name, and congruent with the actual file name) so future features can take advantage of the same solution.
Tested on linux and …

fix: restore environment before launching external programs

---

tagstudio/src/qt/modals/tag_search.py
tagstudio/src/qt/widgets/preview_panel.py

fixes #730
fixed and works (afaik) with new tag result sorting
also gave first_tag_id a more accurate type hint

Fix: [Bug] Fix add on return

---

tagstudio/src/qt/modals/tag_search.py
tagstudio/src/qt/widgets/tag.py

This PR aims to fix #733 by replacing calls to `translate_qobject` with `translate_formatted` inside the `TagWidget` class, as for an unknown reason this seems to cause the application to progressively slow down as more TagWidgets are created and removed over time, and also seemingly causes a memory leak.
The `translate_qobject` issue should be investigated further, however for now this fix should hopefully address the specific issue raised in #733. I've also included a couple small fixes and tweaks to nearby code that I discovered while tracking this down.

fix: replace calls to `translate_qobject` with `translate_formatted` inside `TagWidget` (Fix #733)

---

tagstudio/src/qt/helpers/vendored/ffmpeg.py
tagstudio/src/qt/helpers/vendored/pydub/audio_segment.py
tagstudio/src/qt/helpers/vendored/pydub/utils.py
tagstudio/src/qt/modals/ffmpeg_checker.py
tagstudio/src/qt/widgets/thumb_renderer.py

This PR aims to fix audio waveforms not rendering in macOS builds, plus ensuring that the location of FFmpeg is used by pydub and the new "About" screen.
Note that video thumbnail rendering, video playback, and audio playback all functioned before and after this PR.

fix: have pydub use known ffmpeg+ffprobe locations

---

tagstudio/src/core/library/alchemy/library.py

Tag searches now include searching for tag aliases. Fixes #682

fix: use tag aliases in tag search

---

tagstudio/src/core/library/alchemy/library.py

Fixes #723 by retaining the initial entry ID order when returning results from `get_entries_full().

fix: keep initial id order in `get_entries_full()` (Fix #723)

---

tagstudio/resources/translations/en.json
tagstudio/src/core/utils/refresh_dir.py
tagstudio/src/qt/ts_qt.py

This PR drastically reduces the amount of time needed to add new file entries to the library after refreshing by adding all entries to the database in a single operation.

perf: add all new library entries at once

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/core/utils/missing_files.py
tagstudio/src/qt/modals/delete_unlinked.py
tagstudio/src/qt/modals/fix_unlinked.py
tagstudio/src/qt/modals/relink_unlinked.py
tagstudio/src/qt/widgets/preview/preview_thumb.py
tagstudio/tests/macros/test_missing_files.py
tagstudio/tests/test_library.py

This PR extends the fixes added in #720, which was an extension of #653, and makes the following additional changes:
- Refactors missing_files.py with more consistent an unambiguous naming
- Fixes a bug where a loop would try to remove an item from the list it was iterating over, resulting in matched results being skipped each loop
- Fixed a test that was built with the above issue present
- Uses the `GLOBAL_IGNORE_SET` as part of the file matching process

fix: refactor and fix bugs with missing_files.py

---

tagstudio/src/qt/widgets/item_thumb.py

This PR fixes the critical issue of not being able to ctrl+deselect items in the thumbnail grid (#732) by reverting the "thumb_button.clicked -> thumb_button.pressed" changes made in #556, which caused the drag and drop issue described in #706, which was later addressed in #710, however with the side effect of causing the selection issue described in #732.
This PR knowingly comes with a regression to the click behavior prior to #555, however the time sensitivity and severity of #732 outweighs the enhancement requested in #555.

fix(ui): revert all `item_thumb` "pressed" changes (Fix #732)

---

tagstudio/resources/translations/en.json
tagstudio/src/core/library/alchemy/library.py
tagstudio/src/qt/widgets/migration_modal.py
tagstudio/tests/test_json_migration.py

This PR extends #604 to include parity checking for tag names themselves. This also fixes a bug where user-edits to built-in tag names and shorthands were not carried over from JSON libraries.

fix: check for tag name partiy during JSON migration

---

tagstudio/resources/translations/en.json
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/tag_box.py

This PR adds a new menu shortcut to bring up a tag search box and add a tag to the currently selected entries. This can also be accessed with a new key combination: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>.
This PR also changes the left-click behavior of tags from searching for the tag in the library to editing the tag. This matches the behavior of how selecting tag colors works, and I feel this is much more ergonomic than searching for tags - especially when accidentally clicked. Both the edit and search options still remain in the right-click context menu.

ui: shortcut to add tags to selected entries; change click behavior of tags to edit

---

tagstudio/src/qt/widgets/thumb_button.py

This PR changes which `ColorRole` is used on Windows to select the system accent color. This seems to be a change made in PySide 6.8.0, however I can't find the change documented anywhere. The `QPalette.ColorRole.AlternateBase` `ColorRole` also doesn't seem to be quite the same as the old `QPalette.ColorRole.Accent` color, so I've had to boost the lightness value a bit here. Other platforms (only tested on macOS) still use the `QPalette.ColorRole.Accent` value since it works, while the `QPalette.ColorRole.AlternateBase` does not.
Fixes #668.

fix(ui): restore Windows accent color on PySide 6.8.0.1 (Fix #668)

---

tagstudio/src/qt/ts_qt.py

This PR addresses an "issue" where macOS (and probably Linux) uses a lighter/different dark theme than the one found on Windows 10, along with some other odd color palette quirks such as the inactive button text turning black.
This PR sets the window and button background colors to a specific value, rather than relying on the OS to hint at which color to use.

fix(ui): use consistent dark mode colors for all systems

---

tagstudio/src/qt/modals/tag_search.py
tagstudio/src/qt/widgets/tag.py
tagstudio/src/qt/widgets/tag_box.py

This PR partially fixes where the "Search for Tag" right-click option for tags. This feature remains broken for the "Tag Manager" modal, as fixing that would require annoyingly modifying a wasps nest of UI tests which is way beyond what I'd like to fix right now.

fix(ui): (mostly) fix right-click search option on tags

---

docs/usage.md

I just saw this while reading up on categories, figured I'd submit a change so it doesn't go unnoticed

Correct Cagegory to Category in docs/usage.md

---

docs/index.md

image wasn't showing in the docs

fix(docs): fix image not rendering

---

tagstudio/src/core/query_lang/tokenizer.py

close #764 
This refactors a function in the tokenizer to allow colons to be included in the tag name,
the logic functions exactly the same otherwise

Fix: Error searching for tag containing a colon

---

tagstudio/resources/translations/en.json
tagstudio/src/core/library/alchemy/enums.py
tagstudio/src/core/library/alchemy/library.py
tagstudio/src/qt/ts_qt.py
tagstudio/tests/test_search.py

This PR introduces better error handing for the search syntax system that prevents various errors from occurring.
> [fix: move path_strings var inside with block](https://github.com/TagStudioDev/TagStudio/commit/c346ea96a75084cfcc094345628048338a658f9b)
This change fixes #776 by preventing the errors that were raised when the `path: ` keyword was used with a space following the colon.
The other commits focus on providing error handling by catching `ParsingError`s raised by the search syntax system. This prevents the errors causing #777 as well as #764, however it's not a full fix for the issues described in #764 and #765 is still required. 
***
Fixes #776, Fixes #777

fix: catch `ParsingError`

---

tagstudio/src/qt/widgets/migration_modal.py

This PR adds a try/except block around the creation of the `migration_iterator`, including its lambda. It's goal is to (hopefully) help catch and diagnose issues such as the fleeting one found in #772.

refactor: wrap migration_iterator lambda in a try/except block

---

tagstudio/src/core/enums.py
tagstudio/src/core/library/alchemy/fields.py
tagstudio/src/core/library/alchemy/library.py

This PR fixes a couple of issues with the library database listed below, patches existing libraries with the affected issues from v9.5.0-pr1, and bumps the DB_VERSION to 7.
Fixes #768
Fixes #774

fix: patch incorrect description type & invalid disambiguation_id refs

---

tagstudio/src/qt/ts_qt.py

A plain an simple "hide menu actions that should only be accessible in a library while in a library" PR. Some light refactoring of action names involved since some had very odd names.
Closes #692
Closes #462
Addresses #767 but only on a surface level - I'd rather #769 continue with a proper backend preventative measure
Affects #713

fix(ui): hide library actions when no library is open

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/qt/modals/folders_to_tags.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/item_thumb.py
tagstudio/src/qt/widgets/preview/field_containers.py
tagstudio/src/qt/widgets/tag_box.py
tagstudio/tests/conftest.py
tagstudio/tests/qt/test_field_containers.py
tagstudio/tests/test_library.py

This PR makes several performance improvements to the way that query methods are executed, how toggled badges update entries with tag changes, and how toggled badges update the preview panel.
The main part of this PR is the restructuring of the `get_entries_full()` method, which now queries the tags separately from the base entry query and recombines them into a final Entry object. I was unable to optimize the preexisting query statement itself, however this recombination method provides a huge performance boost (~10x) for large complex libraries - so much so that the badge optimizations have become almost overshadowed by this change.

perf: optimize query methods and reduce preview panel updates

---

tagstudio/src/core/library/alchemy/library.py
tagstudio/src/core/library/alchemy/visitors.py
tagstudio/src/qt/ts_qt.py
tagstudio/tests/test_library.py

This PR adds "smartcase" style path searches and allows for non-glob searches to still return results. Smartcase searches will act as case-insensitive when the entire query is lowercase, but will turn case-sensitive if one or more capital letters are present in the query. Meanwhile the glob detection is now based on whether or not a query starts or ends with a "*" character.
This PR also limits the number of results in the path autocomplete list to 100 items to avoid sluggish search typing that scales with the size of the library.
`path: temp`
- Returns all paths that have "temp" **(Case insensitive)** somewhere in the name. 
`path: Temp`
- Returns all paths that have "Temp" **(Case sensitive)** somewhere in the name.
`path: *temp*`
- Returns all paths that have "temp" **(Case …

feat: add smartcase and globless path searches

---

tagstudio/src/qt/modals/about.py
tagstudio/src/qt/modals/delete_unlinked.py
tagstudio/src/qt/modals/drop_import.py
tagstudio/src/qt/modals/fix_dupes.py
tagstudio/src/qt/modals/fix_unlinked.py
tagstudio/src/qt/modals/mirror_entities.py
tagstudio/src/qt/modals/relink_unlinked.py
tagstudio/src/qt/modals/tag_database.py
tagstudio/src/qt/modals/tag_search.py
tagstudio/src/qt/translations.py
tagstudio/src/qt/ts_qt.py
tagstudio/src/qt/widgets/color_box.py
tagstudio/src/qt/widgets/item_thumb.py
tagstudio/src/qt/widgets/landing.py
tagstudio/src/qt/widgets/migration_modal.py
tagstudio/src/qt/widgets/preview/field_containers.py
tagstudio/src/qt/widgets/preview/file_attributes.py
tagstudio/src/qt/widgets/preview/preview_thumb.py

This PR restores the use of the `translate_formatted()` method (now refactored as just `format()`) that was removed in #817 in order to catch KeyErrors raised from invalid formatting keys being added in the translation files and passed to `.format()` calls.
- Tested on:
- Tested for:
***
Closes #827, along with the fixed translations in #826.

fix: restore `translate_formatted()` method

---

tagstudio/tests/conftest.py
tagstudio/tests/macros/test_dupe_entries.py
tagstudio/tests/macros/test_missing_files.py
tagstudio/tests/macros/test_refresh_dir.py
tagstudio/tests/test_json_migration.py
tagstudio/tests/test_translations.py

Test for the following problems:
- translation keys that are present in en.json not being present in other translations
- translation keys that are present other translations not being present in en.json
- translations using format keys that aren't used by the equivalent in en.json
-  translations not using format keys that *are* used by the equivalent in en.json
(Note that these tests currently fail and that that is intentional as the translations are incorrect at the moment)

feat: add tests for translations

---

src/tagstudio/qt/widgets/preview/preview_thumb.py
src/tagstudio/qt/widgets/thumb_renderer.py

Resolves #848 by catching the `NotImplementedError` raised by attempting to render "Float16" JPEG-XL files, which are not currently supported by the pillow_jxl module.

fix: catch NotImplementedError for Float16 JPEG-XL files

---

tests/test_translations.py

Changes the structure of the translation test, without changes in tested behaviour, to log all problems that can be found instead of just the first.

fix: log all problems in translation test

---

src/tagstudio/qt/modals/ffmpeg_checker.py

A string for a log message was missing the `f` to make it a format string.

fix(ffmpeg): remove redundant log statement

---

nix/package/default.nix

Impacts users using GTK-related Qt platform plugins, must wrap application.
See https://github.com/NixOS/nixpkgs/issues/149812 for details.
-   [x] Linux x86 (NixOS)
-   [ ] PyInstaller executable 
-   [x] Nix package building

fix(nix/package): account for GTK platform

---

src/tagstudio/qt/ts_qt.py

Removes hard-coded palette for platforms that are heavily themeable.
-   [x] Linux x86 (NixOS)
-   [ ] PyInstaller executable 
-   [x] Nix package building

fix(ts_qt): do not set palette for Linux-like systems that offer theming

---

nix/package/default.nix
src/tagstudio/qt/ts_qt.py
src/tagstudio/resources/tagstudio.desktop

Provides a desktop file, and exposes it and the relevant icon for the Nix package.
Fixes: #415
Fixes: #422
Fixes: #847
Note that I cannot test pinning functionality as I do not use a desktop environment. Would appreciate help with testing that. Otherwise, I will create a virtual machine.
-   [x] Linux x86 (NixOS)
-   [ ] PyInstaller executable 
-   [x] Nix package building

feat(resources): provide desktop file

---

flake.lock
flake.nix
nix/shell.nix

Resolves problem of duplicated nixpkgs input as noted in https://github.com/TagStudioDev/TagStudio/issues/847#issuecomment-2727624004, will now only be consumed by the Nix shell.
Long term, an alternative like uv2nix could be used in the shell to remove any kind of pinning. That is out of scope for now, especially when there is no lock file being used in the repo yet.
-   [x] Linux x86 (NixOS)

fix(flake): remove pinned input, only consume in Nix shell

---

src/tagstudio/qt/translations.py

This PR aims to hide non-functional keyboard mnemonics on macOS as the system does not support them. It aims to do this by filtering out mnemonic indicators from translation files while keeping escaped ampersands intact.
This change will also hide any non-menu mnemonics on macOS that may be added in #843 (menu mnemonics are already hidden by the system's native menubar).

fix: hide mnemonics on macOS

---

src/tagstudio/core/library/alchemy/library.py
src/tagstudio/core/library/alchemy/visitors.py

Replaces instances of `UNION ALL` with `UNION` to prevent infinite recursive loops in SQL statements. This also aligns with the intended behavior of these statements where the returned results should be unique (at least in library.py). Fixes #875. 
From the [SQLite docs](https://www.sqlite.org/lang_with.html):
> If a UNION operator connects the initial-select with the recursive-select, then only add rows to the queue if no identical row has been previously added to the queue. Repeated rows are discarded before being added to the queue even if the repeated rows have already been extracted from the queue by the recursion step. If the operator is UNION ALL, then all rows generated by both the initial-select and the recursive-select are always added to the queue even if they are repeats. When …

fix: use UNION instead of UNION ALL

---

src/tagstudio/qt/helpers/file_opener.py

[Refactor] type fixes and minor improvements to file_opener.py

---

src/tagstudio/resources/translations/de.json
src/tagstudio/resources/translations/en.json

Remove an unescaped ampersand from the "about.description" translation key which caused the text to render incorrectly. This could have been addressed by escaping the ampersand (e.g. "&&") but I've opted to replace it with the word "and" instead.
Before:
After:

fix: remove unescaped ampersand from "about.description"

---

CONTRIBUTING.md

Small PR - Commit 226d18e743b94943503521ae7d7319ad84f7db5b renamed agents to algorithms. This PR adjusts sources to changes.

docs: update Thumb Renderer source

---

src/tagstudio/qt/widgets/thumb_renderer.py

fix: Prevent Dangling File Handle

---

src/tagstudio/qt/widgets/preview/preview_thumb.py

Improves responsiveness of opening GIF entry by passing file path directly to QMovie instead of opening the image and copying it twice.
Fixes #816.
-   [x] Basic functionality (GIF, APNG, WEBP)

feat: improve responsiveness of GIF entries

---

tagstudio.spec

Minor changes to pathex and datas
-   [x] PyInstaller executable

build: Minor improvements to PyInstaller.

---

src/tagstudio/qt/ts_qt.py
src/tagstudio/resources/translations/en.json

This PR makes a couple tweaks to the Recent Libraries menu item:
1. Add a more specific error message when trying to open a library location that no longer exists *(while keeping in mind that the full library path may not always be shown anymore, and in the future library files may not be in the same location as the folders they use)*
2. Increase the recent library list limit from 5 to 10

ui: recent libraries list improvements

---

src/tagstudio/qt/flowlayout.py

- Added `@override` decorators and removed `# noqa: N802` comments.
- Changed parameter names in override methods to match the base methods.
- Used `setProperty` to assign the "ignore_size" property to `FlowWidget`.
- Fixed `HeightForWidth` to return `int` instead of `float` since the base method is annotated to return `int`.
- Simplified the if statement in line 127.

[Refactor] Type fixes and minor improvements to flowlayout.py

---

src/tagstudio/qt/widgets/media_player.py

This PR replaces the manual video looping logic with the QMediaPlayer.setLoops() method to seamlessly loop videos instead of stopping and starting them again.

fix(ui): seamlessly loop videos

---

src/tagstudio/qt/ts_qt.py
src/tagstudio/resources/translations/en.json

Add the ability to select unselected thumbnails while unselecting selected thumbnails.. thus inverting your selection. I found that when I'm trying to go through a lot of tags sometimes it's more of a Boolean operation where I select a bunch to tag with one thing but want to select all the opposite ones to tag them with the other tag. I used what was considered a fairly common hotkey for invert selection (at least it's the one that comes up when you google "hotkey to select inverse")
Sorry I didn't open an issue first, It seemed small enough of a thing I didn't mind to throw it together as I didn't see any mention of anything similar in any issues or on the roadmap and I wont be offended if it's rejected but it certainly would be helpful to have :)
-   [x] Windows …

feat: add ability to invert selection

---

src/tagstudio/qt/widgets/preview/field_containers.py

Small refactors to `qt/widgets/preview/field_containers.py` in order to fix warnings.
Also adds a temporary modal for DATETIME fields so that they can be edited at all, before proper editing support comes in 9.6.
Note: This PR doesn't conflict with #904 as DATETIME fields were overlooked there. I would suggest merging #904 before this PR and then adding the settings integration for DATETIME fields to this PR (#904 has been sitting for a while now so this way it should get resolved sooner overall).

feat: temporary modal to edit datetime fields and small refactors

---

src/tagstudio/core/global_settings.py
src/tagstudio/qt/widgets/preview/field_containers.py
src/tagstudio/qt/widgets/preview/file_attributes.py

- move datetime formatting according to the current settings to the global settings class
- integration date format settings with datetime field formatting

feat: datetime fields settings integration

---

tests/conftest.py
tests/qt/test_file_path_options.py
tests/qt/test_global_settings.py
tests/test_driver.py

Replaced `dev/null` path with a universal `temp_dir` function that persists through the test session and cleans itself up afterwards to function identically but runs on windows as well as others? I don't have another platform to test this on so it will need to be tested.
<sub>Sorry, it was bugging me I wanted tests to pass xD<sub>

fix(test): Fix tests to pass on windows without disrupting other platforms

---

flake.lock
flake.nix
nix/package/default.nix
nix/package/shiboken6-fix-include-qt-headers.patch

Temporary solution for #915, long term should involve a proper upgrade on PySide6. This only applies the override if a later version of PySide6 is found. Again, this should only be temporary, my poor machine took a beating compiling this; does give some motivation for exploring Cachix further, however.
As far as I have been able to tell, Qt does not need any override treatment.

fix(nix/package): override PySide6 if later version is being used

---

src/tagstudio/qt/modals/add_field.py

As requested in https://github.com/TagStudioDev/TagStudio/issues/463.
I can only test on macOS, where the Return key is sent. I assume on other platforms it would Enter. This covers both, but needs to tested on Linux/Windows. 

feat: Press enter when adding fields

---

src/tagstudio/qt/modals/folders_to_tags.py
tests/qt/__snapshots__/test_folders_to_tags.ambr

2 main things are changed for the `folders_to_tags` macro.
1. Tagging starts with folders in the root of the TagStudio directory (i.e. on the same level as .TagStudio). 
2. Parent tags are assigned.
Tested on my library of \~850 images, nested up to 3 layers of folders deep.

fix: add parent tags to `folders_to_tags` macro and start tagging at root folder

---

src/tagstudio/qt/resource_manager.py

- Type annotation fixes
- Made `ResourceManager` singleton
- Simplified how the data is loaded and cached

refactor: resource_manager.py

---

src/tagstudio/qt/modals/build_tag.py
src/tagstudio/qt/modals/settings_panel.py
src/tagstudio/qt/modals/tag_color_manager.py
src/tagstudio/qt/modals/tag_database.py
src/tagstudio/qt/modals/tag_search.py
src/tagstudio/qt/ts_qt.py
src/tagstudio/qt/widgets/color_box.py
src/tagstudio/qt/widgets/landing.py
src/tagstudio/qt/widgets/panel.py
src/tagstudio/qt/widgets/preview/field_containers.py
src/tagstudio/qt/widgets/preview_panel.py

- few type improvements to both landing.py and panel.py
- renamed a method in the `PanelModal` class (in panel.py) and updated all references in other files

Type improvements to landing.py and panel.py

---

CONTRIBUTING.md
STYLE.md

Splits the style guide into a separate file, and documents the intended future structure of the qt part of the code base.
Not applicable

doc: Add QT MVC structure to style guide

---

src/tagstudio/qt/main_window.py

- Adds type annotations to the `MainWindow` class in `main_window.py` to address Pyright's [`reportUninitializedInstanceVariable`](https://docs.basedpyright.com/v1.29.0/configuration/config-files/#reportUninitializedInstanceVariable) warning and few more type improvements,
- Removes two overridden methods that appear to be unused.

Improve main_window.py

---

src/tagstudio/core/library/alchemy/library.py

The `get_tag_by_name` method was broken. I also fixed a warning in `get_tag` and extended `search_library` to support searching without a page size (just internally; i.e. no UI changes).
(This is kind of just a mix of stuff I came across. Since this isn't a lot changes I figured splitting into multiple PRs would be unnecessary work)

fix(library): get_tag_by_name

---

src/tagstudio/qt/ts_qt.py

During the library initialization step, ensure that the initial browsing state pulls its values from the current UI state.
Fixes #1007.

fix: ensure initial browsing state uses UI values

---

src/tagstudio/qt/view/widgets/preview/preview_thumb_view.py

Due to a hardcoded maximum size for preview thumbnails, preview thumbnails don't scale to fit all the space available to the PreviewThumb Component. Since a limit is needed to avoid the performance hit that massive images would incur, I have change the limit to be the screen size since the component shouldn't be bigger than that anyways.

fix: preview thumbnails don't scale as large as they could

---

src/tagstudio/qt/helpers/qslider_wrapper.py
src/tagstudio/qt/view/widgets/preview/preview_thumb_view.py
src/tagstudio/qt/widgets/media_player.py

This PR makes a few design and QoL tweaks to the media player:
- Simplified layout and style
- Black hover overlay replaced with gradient behind controls
- Added deadzone around player controls where clicking won't pause/unpause
- Added more generous margins between controls
- Fixed clicking to jump far into unbuffered media
- Misc code cleanup
Known (preexisting) issue: Clicking to jump to a presumably unbuffered section of media does now allow for continuous dragging until clicked again.
Before:
After:

ui: tweak media player style and behavior

---

src/tagstudio/core/utils/missing_files.py
src/tagstudio/qt/controller/widgets/preview/preview_thumb_controller.py
src/tagstudio/qt/helpers/file_deleter.py
src/tagstudio/qt/helpers/file_opener.py
src/tagstudio/qt/widgets/preview/file_attributes.py
src/tagstudio/qt/widgets/thumb_renderer.py

Fixes #989 
When a unlinked entry has a folder with the same name:
- It can’t be deleted.
- It can’t be opened or revealed
- The thumbnail will show as unlinked
- File stats are hidden.
- Considered as unlinked in the Fix Unlinked Entries menu (which was the behaviour even before this PR)
Let me know if there is any changes you would like me to make :)
-   [x] Linux ARM

fix: folders with names of unlinked entries are linked

---

src/tagstudio/main.py

This PR adds version arguments (`-v` and `--version` ) to TagStudio's [main entrypoint](https://github.com/TagStudioDev/TagStudio/blob/3489e159a503d67e1b87e8bcd4fc5be72f944505/src/tagstudio/main.py#L19).
Version information is formatted as follows: `TagStudio v{VERSION} {VERSION_BRANCH}`
Examples:
```
$ tagstudio --version
TagStudio v9.5.3
```
```
$ tagstudio --version
TagStudio v9.5.4 Pre-Release
```
Seeing as this is only a small change, I've opted to open this PR without prior discussion.

feat: cli version argument

---

src/tagstudio/core/global_settings.py
src/tagstudio/qt/modals/settings_panel.py
src/tagstudio/qt/view/widgets/preview/preview_thumb_view.py
src/tagstudio/qt/widgets/item_thumb.py
src/tagstudio/qt/widgets/thumb_renderer.py
src/tagstudio/resources/translations/en.json

#930 is a blocker for me because I mainly use it for sound at the moment.
Haven't wrote python for a while and isn't really familiar with the current convention for python so let me know if anything need fixing.

feat: add settings to disable automatic thumbnail generation for sound

---

src/tagstudio/qt/widgets/preview/field_containers.py

This PR addresses (but does not solve the root issue of) #1074 by adding a cutoff to the `get_tag_categories()` method inside the `FieldContainers` class, preventing infinite loops in the event of cyclical tag relationships. Surprisingly this was seemingly not needed in the `get_tag_hierarchy()` method of the `Library` class. 
*No more freezing in the preview panel, tags load as previously done*

fix: add loop cutoff to get_tag_categories()

---

src/tagstudio/qt/main_window.py

Reimplement KDE's system for autogenerating mnemonics[^1] which also incorporates `&` markings when present, but doesn't require them to be present.
Currently only works for the drop downs but could probably be adopted for the menu bar as well.
Example - File menu with all `&` removed from translations:
Possible Future PRs:
- removing `&` from translations where now unnecessary
- adopting it for the QMenuBar at the top
- adopting it for buttons in windows and the like
[^1]: See [Wiki](https://api.kde.org/frameworks/kirigami/html/classMnemonicAttached.html), …

feat: auto mnemonics

---

src/tagstudio/qt/widgets/migration_modal.py

This fixes an issue where the Migration Modal would throw an error when attempting to finish due to an internal constant not being refactored properly and still using the old invalid Library class attribute. Pyright caught this, but mypy did not (see #1061).

fix: update SQL_FILENAME to import from new constant

---

src/tagstudio/qt/widgets/thumb_renderer.py

This fixes #1091, which was caused by MIME types on the tested Linux systems to assume that `.vtf` files have the "Image" MIME type and therefore were sent to the standard image renderer rather than the bespoke VTF renderer. I've chosen to reorder the ""switch"" statement to put pseudo image types before the standard image types in order to retain the functionality of the MIME fallback while also prioritizing these specific formats.
While I did not run any specific performance measurement tests, I don't believe this will make an impact since each of these checks should be O(1) since they're just set membership checks - I'd love a second opinion on this though.
-   [ ] Linux …

fix: reorder renderer types to fix early false positives

---

src/tagstudio/core/global_settings.py
src/tagstudio/qt/controller/widgets/preview/preview_thumb_controller.py
src/tagstudio/qt/helpers/file_opener.py

Fixes #1036 by adding a new `windows_start_command` option in the `settings.toml` file which toggles the pre-#667 file opener behavior on Windows. This is a niche option so I decided to not include it in the GUI and only make it available when editing the file itself.
In order to test the full functionality of this PR, the option must be set to `true`. 
I tested this on Windows 10 with "Photos" version 2025.11070.8001.0 by opening .jpg files with and without the option. Without it, I get the following message about 50% of the time with some times having the zoom locked and other times having no apparent issue at all.
-   [x] Basic …

fix: add option to use old Windows 'start' command

---

src/tagstudio/core/enums.py
src/tagstudio/core/global_settings.py
src/tagstudio/qt/cache_manager.py
src/tagstudio/qt/modals/settings_panel.py
src/tagstudio/qt/pagination.py
src/tagstudio/qt/ts_qt.py
src/tagstudio/resources/translations/en.json

This moves the previous (undocumented) thumbnail cache size setting from the old `TagStudio.ini` file to the newer `Settings.toml` file as `thumb_cache_size` and exposes it to the settings panel GUI.
The minimum allowed value is 10 MiB as to not cause issues with the underlying `CacheManager` system.

feat(ui): add thumb cache size setting to settings panel

---

src/tagstudio/qt/mixed/media_player.py

Fix #1053 by always showing the first frame of a video in the preview panel when selecting it. Also fixed the related issue of autoplay not always playing automatically depending on the player's pause state.
Closes #1059.

fix: always show first frame of video; autoplay will always play

---

src/tagstudio/qt/previews/renderer.py

If an ePub contains no ComicInfo.xml the first image should be used as the fallback thumbnail.
Currently, the last image will be used due to a missing `break` after the first image is loaded.
Fixes https://github.com/TagStudioDev/TagStudio/issues/1051 (at least for zip based ePubs)
* [NoComicInfo.cbz.zip](https://github.com/user-attachments/files/22198469/NoComicInfo.cbz.zip)
* [NoPages.cbz.zip](https://github.com/user-attachments/files/22198471/NoPages.cbz.zip)
Again renamed because of GitHub upload limitiations.

fix: use first file as epub thumbnail instead of the last.

---

pyproject.toml
src/tagstudio/qt/previews/renderer.py

Fixes https://github.com/TagStudioDev/TagStudio/issues/1117
* [WithComicInfo.cb7.zip](https://github.com/user-attachments/files/22222724/WithComicInfo.cb7.zip)
* [NoComicInfo.cb7.zip](https://github.com/user-attachments/files/22222725/NoComicInfo.cb7.zip)
The usual extension changes.

feat: render .cb7 thumbnails.

---

src/tagstudio/core/library/ignore.py

Fixes #1126 by removing unnecessary logic that didn't respect trailing slash ignore patterns.

fix: respect trailing slash patterns in glob

---

src/tagstudio/qt/mixed/item_thumb.py

If an extension only required the `ext_badge` it would not hide the `count_badge`.
This seems to fix #1125 for me

fix: always hide duration badge on non video ext

---

src/tagstudio/qt/mixed/media_player.py

This change ensures the user clicked with the left mouse button before togging the media player. With no checks, it will also pause on right click. 
Fixes issue: https://github.com/TagStudioDev/TagStudio/issues/1151

fix: toggle play only with left mouse button click

---

src/tagstudio/core/library/alchemy/visitors.py

Fixes searching `<Tag A> AND <Tag A>` returning no results, when it should return the same results as `<Tag A>` ([#951](https://github.com/TagStudioDev/TagStudio/issues/951)).
I'm not very familiar with the backend and haven't done very in-depth testing, so please point out if this causes any unintended side effects.
Tweaked the `__separate_tags()` method in `src/tagstudio/core/library/alchemy/visitors.py` to, rather than a list, use a set for collecting the tag IDs of each term of an AST `ANDList` and `ORList` to prevent duplicate tag IDs from being returned.
The SQL query built from the search `<Tag A> AND <Tag A>` will always fail due to this section:
```
WHERE tag_entries.tag_id IN (1, 1)
GROUP BY tag_entries.entry_id
HAVING count(DISTINCT tag_entries.tag_id) = 2
```
Since it's …

fix: Fix searching `A AND A` returning no results
